name: Deploy staging
on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging branch
        uses: actions/checkout@v2
        with:
          ref: staging
      - name: Install dependencies
        run: npm install && cd functions && npm install && cd ..
      - name: Build application
        env:
          CDC_ENVIRONMENT: staging
          CDC_VERSION: 1
          CDC_FIREBASE_API_KEY: AIzaSyCpsaP2dmFTMWeltITf_SkAIsCU4Wa_KGM
          CDC_FIREBASE_AUTH_DOMAIN: stg-comprar-desde-casa.firebaseapp.com
          CDC_FIREBASE_DATABASE_URL: https://stg-comprar-desde-casa.firebaseio.com
          CDC_FIREBASE_PROJECT_ID: stg-comprar-desde-casa
          CDC_FIREBASE_STORAGE_BUCKET: stg-comprar-desde-casa.appspot.com
          CDC_FIREBASE_MESSAGING_SENDER_ID: 669485618780
          CDC_FIREBASE_APP_ID: 1:669485618780:web:cabb916efcb21440c0f899
          CDC_FIREBASE_MEASUREMENT_ID: G-FW2Z7EZG6P
        run: npm run build
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npx firebase deploy --project=stg-comprar-desde-casa