name: Deploy production
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install && cd functions && npm install && cd ..
      - name: Build application
        env:
          CDC_ENVIRONMENT: production
          CDC_VERSION: 1
          CDC_FIREBASE_API_KEY: AIzaSyCeMIytvcgakZJfwf1B-8qfujq7b9VPZqk
          CDC_FIREBASE_AUTH_DOMAIN: pedime-lo-que-quieras.firebaseapp.com
          CDC_FIREBASE_DATABASE_URL: https://pedime-lo-que-quieras.firebaseio.com
          CDC_FIREBASE_PROJECT_ID: pedime-lo-que-quieras
          CDC_FIREBASE_STORAGE_BUCKET: pedime-lo-que-quieras.appspot.com
          CDC_FIREBASE_MESSAGING_SENDER_ID: 691587000634
          CDC_FIREBASE_APP_ID: 1:691587000634:web:89da965bca31e21a688803
          CDC_FIREBASE_MEASUREMENT_ID: G-SKMV86KYJH
        run: npm run build
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npx firebase deploy --project=pedime-lo-que-quieras