name: DEV - Deploy to Firebase
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: dev
      - name: Install Dependencies
        run: npm install && cd functions && npm install && cd ..
      - name: Build
        run: npm run build
      - name: Archive App Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public
      - name: Archive Firebase
        uses: actions/upload-artifact@master
        with:
          name: public
          path: firebase.*
      - name: Archive Firebase functions
        uses: actions/upload-artifact@master
        with:
          name: public
          path: functions
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: dev
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
      - name: Deploy to Firebase
        run: npm install firebase-tools && ./node_modules/.bin/firebase deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} 