name: DEV - Deploy to Firebase
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@dev
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Artifact
        uses: actions/upload-artifact@dev
        with:
          name: public
          path: public
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@dev
      - name: Download Artifact
        uses: actions/download-artifact@dev
        with:
          name: public
      - name: Deploy to Firebase
        run: npm install -g firebase-tools -y && firebase deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} 